/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petcafe;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahaf
 */
public class petCafeForm extends javax.swing.JFrame {

    /**
     * Creates new form petCafeForm
     */
    public petCafeForm() {
        super("Pet Cafe");
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(400, 800);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        FormPanel = new javax.swing.JPanel();
        EmployeeCard = new javax.swing.JPanel();
        EmloyeeInfoLabel = new javax.swing.JLabel();
        EmployeeNameLabel = new javax.swing.JLabel();
        EmployeePassLabel = new javax.swing.JLabel();
        EmployeeNameField = new javax.swing.JTextField();
        SingInButton = new javax.swing.JButton();
        SingUpButtom = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        EmplyeeIDLabel1 = new javax.swing.JLabel();
        EmployeeIDField1 = new javax.swing.JTextField();
        ServicesCard = new javax.swing.JPanel();
        ClientInfoLabel = new javax.swing.JLabel();
        OwnerNameLabel = new javax.swing.JLabel();
        PetNameLabel = new javax.swing.JLabel();
        MobileLabel = new javax.swing.JLabel();
        OwnerNameField = new javax.swing.JTextField();
        PetNameField = new javax.swing.JTextField();
        MobileField = new javax.swing.JTextField();
        PetLabel = new javax.swing.JLabel();
        DogRadioButton = new javax.swing.JRadioButton();
        CatRadioButton = new javax.swing.JRadioButton();
        PetServicesLabel = new javax.swing.JLabel();
        FeedingCheckBox = new javax.swing.JCheckBox();
        DogWalkingCheckBox = new javax.swing.JCheckBox();
        CatBreedingChechBox = new javax.swing.JCheckBox();
        GroomingLabel = new javax.swing.JLabel();
        HairCutCheckBox = new javax.swing.JCheckBox();
        NailClippinCheckBox = new javax.swing.JCheckBox();
        VetLabel = new javax.swing.JLabel();
        VaccineCheckBox = new javax.swing.JCheckBox();
        ExaminationChechBox = new javax.swing.JCheckBox();
        ClearButton = new javax.swing.JButton();
        PrintButton = new javax.swing.JButton();
        AddrButton = new javax.swing.JButton();
        CafeServiceLabel = new javax.swing.JLabel();
        NoteLabel = new javax.swing.JLabel();
        PersonSpinner = new javax.swing.JSpinner();
        submitButton = new javax.swing.JButton();
        QueriesCard = new javax.swing.JPanel();
        QueriesLabel = new javax.swing.JLabel();
        QuerierNameLabel = new javax.swing.JLabel();
        querierNameTextField = new javax.swing.JTextField();
        QuerierMoblieLable = new javax.swing.JLabel();
        QuerierMoblieTextField = new javax.swing.JTextField();
        partitiontLabel = new javax.swing.JLabel();
        recordedFilesCheckBox = new javax.swing.JCheckBox();
        ShowButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        NewEmployeeCard = new javax.swing.JPanel();
        NewEmployeeLabel1 = new javax.swing.JLabel();
        NEmployeeNameLabel1 = new javax.swing.JLabel();
        NEmolyeeNameField1 = new javax.swing.JTextField();
        EmployeeSSNLabel2 = new javax.swing.JLabel();
        NEmployeeSSNField1 = new javax.swing.JTextField();
        ClearNewEIButton1 = new javax.swing.JButton();
        NewEmployeeIDLabel1 = new javax.swing.JLabel();
        NewEmployeeIDField1 = new javax.swing.JTextField();
        AddNewEmployeeButton1 = new javax.swing.JButton();
        updateEmployeeCaredPanel1 = new javax.swing.JPanel();
        updateEmplyeeInfoLabel1 = new javax.swing.JLabel();
        EmployeeIDLabel1 = new javax.swing.JLabel();
        EmplyeeIdField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NewNameField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NewSNNField1 = new javax.swing.JTextField();
        updateButton1 = new javax.swing.JButton();
        DeletEmplyeeCard = new javax.swing.JPanel();
        deletEmployeeLabel3 = new javax.swing.JLabel();
        EmployeeIdLabel3 = new javax.swing.JLabel();
        DEmployeeIDTextField1 = new javax.swing.JTextField();
        deletEmployeeButton1 = new javax.swing.JButton();
        MangerCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mangerIdTextField1 = new javax.swing.JTextField();
        mangerName = new javax.swing.JLabel();
        mangerNameTextField1 = new javax.swing.JTextField();
        mangerPssLabel5 = new javax.swing.JLabel();
        MSignInButton1 = new javax.swing.JButton();
        mangerPasswordField1 = new javax.swing.JPasswordField();
        MsginOutButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        EmployeeMenu = new javax.swing.JMenu();
        mangerMenuItem1 = new javax.swing.JMenuItem();
        newEmployeeMenuItem1 = new javax.swing.JMenuItem();
        UpdateInfoMenuItem1 = new javax.swing.JMenuItem();
        deletEmployeeMenuItem1 = new javax.swing.JMenuItem();
        singOutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormPanel.setLayout(new java.awt.CardLayout());

        EmloyeeInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        EmloyeeInfoLabel.setText("Employee informations:");

        EmployeeNameLabel.setText("Name:");

        EmployeePassLabel.setText("Password:");

        SingInButton.setText("Sing in");
        SingInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingInButtonActionPerformed(evt);
            }
        });

        SingUpButtom.setText("Sing up");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        EmplyeeIDLabel1.setText("ID:");

        javax.swing.GroupLayout EmployeeCardLayout = new javax.swing.GroupLayout(EmployeeCard);
        EmployeeCard.setLayout(EmployeeCardLayout);
        EmployeeCardLayout.setHorizontalGroup(
            EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCardLayout.createSequentialGroup()
                .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmployeePassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmplyeeIDLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmployeeNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(EmployeeIDField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField)))
                    .addGroup(EmployeeCardLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(EmloyeeInfoLabel))
                    .addGroup(EmployeeCardLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(SingInButton)
                        .addGap(18, 18, 18)
                        .addComponent(SingUpButtom)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        EmployeeCardLayout.setVerticalGroup(
            EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(EmloyeeInfoLabel)
                .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeCardLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(EmplyeeIDLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeCardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNameLabel)
                    .addComponent(EmployeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeePassLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(EmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SingInButton)
                    .addComponent(SingUpButtom))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        FormPanel.add(EmployeeCard, "card2");

        ClientInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ClientInfoLabel.setText("Client information:");

        OwnerNameLabel.setText("Owner name:");

        PetNameLabel.setText("Pet name:");

        MobileLabel.setText("Mobile:");

        OwnerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerNameFieldActionPerformed(evt);
            }
        });

        MobileField.setText("+966");
        MobileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileFieldActionPerformed(evt);
            }
        });

        PetLabel.setText("Pet:");

        buttonGroup.add(DogRadioButton);
        DogRadioButton.setText("Dog");
        DogRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(CatRadioButton);
        CatRadioButton.setText("Cat");
        CatRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatRadioButtonActionPerformed(evt);
            }
        });

        PetServicesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        PetServicesLabel.setText("Pet services:");

        FeedingCheckBox.setText("Feeding pet");

        DogWalkingCheckBox.setText("Dog walking");
        DogWalkingCheckBox.setEnabled(false);
        DogWalkingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogWalkingCheckBoxActionPerformed(evt);
            }
        });

        CatBreedingChechBox.setText("Cat breeding");
        CatBreedingChechBox.setEnabled(false);

        GroomingLabel.setText("Grooming:");

        HairCutCheckBox.setText("Hair cut ");

        NailClippinCheckBox.setText("Nail clippin");

        VetLabel.setText("Vet service:");

        VaccineCheckBox.setText("Vaccine");

        ExaminationChechBox.setText("General Examination");

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        PrintButton.setText("Print ");

        AddrButton.setText("Add new pet");
        AddrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddrButtonActionPerformed(evt);
            }
        });

        CafeServiceLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        CafeServiceLabel.setText("Cafe service :");

        NoteLabel.setText("25$ per person.");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicesCardLayout = new javax.swing.GroupLayout(ServicesCard);
        ServicesCard.setLayout(ServicesCardLayout);
        ServicesCardLayout.setHorizontalGroup(
            ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesCardLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ServicesCardLayout.createSequentialGroup()
                        .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PetServicesLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ServicesCardLayout.createSequentialGroup()
                                    .addComponent(PetLabel)
                                    .addGap(79, 79, 79)
                                    .addComponent(DogRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CatRadioButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ServicesCardLayout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(ClientInfoLabel))
                                .addGroup(ServicesCardLayout.createSequentialGroup()
                                    .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(OwnerNameLabel)
                                        .addComponent(PetNameLabel)
                                        .addComponent(MobileLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(OwnerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                        .addComponent(PetNameField)
                                        .addComponent(MobileField))))
                            .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NailClippinCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CatBreedingChechBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesCardLayout.createSequentialGroup()
                                            .addComponent(VetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(VaccineCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ServicesCardLayout.createSequentialGroup()
                                            .addComponent(GroomingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(HairCutCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(DogWalkingCheckBox)
                                    .addComponent(FeedingCheckBox)
                                    .addComponent(CafeServiceLabel)
                                    .addGroup(ServicesCardLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(PersonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NoteLabel))))
                            .addGroup(ServicesCardLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(ExaminationChechBox)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ServicesCardLayout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(18, 18, 18)
                        .addComponent(ClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(PrintButton)
                        .addGap(10, 10, 10)
                        .addComponent(AddrButton)
                        .addGap(65, 65, 65))))
        );
        ServicesCardLayout.setVerticalGroup(
            ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesCardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ClientInfoLabel)
                .addGap(29, 29, 29)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OwnerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OwnerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetLabel)
                    .addComponent(DogRadioButton)
                    .addComponent(CatRadioButton))
                .addGap(24, 24, 24)
                .addComponent(PetServicesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FeedingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DogWalkingCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CatBreedingChechBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HairCutCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GroomingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NailClippinCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VaccineCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExaminationChechBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CafeServiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoteLabel)
                    .addComponent(PersonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ServicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrintButton)
                    .addComponent(ClearButton)
                    .addComponent(AddrButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        FormPanel.add(ServicesCard, "card3");

        QueriesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        QueriesLabel.setText("Queries");

        QuerierNameLabel.setText("Querier name:");

        QuerierMoblieLable.setText("Querier moblie:");

        partitiontLabel.setText("___________________________________________");

        recordedFilesCheckBox.setText("All recorded files.");

        ShowButton.setText("Show");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout QueriesCardLayout = new javax.swing.GroupLayout(QueriesCard);
        QueriesCard.setLayout(QueriesCardLayout);
        QueriesCardLayout.setHorizontalGroup(
            QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueriesCardLayout.createSequentialGroup()
                .addGap(0, 87, Short.MAX_VALUE)
                .addComponent(partitiontLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(QueriesCardLayout.createSequentialGroup()
                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QueriesCardLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(QueriesLabel))
                    .addGroup(QueriesCardLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QueriesCardLayout.createSequentialGroup()
                                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuerierNameLabel)
                                    .addComponent(QuerierMoblieLable))
                                .addGap(31, 31, 31)
                                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(QuerierMoblieTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(querierNameTextField)))
                            .addComponent(recordedFilesCheckBox)))
                    .addGroup(QueriesCardLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(ShowButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QueriesCardLayout.setVerticalGroup(
            QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesCardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(QueriesLabel)
                .addGap(18, 18, 18)
                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuerierNameLabel)
                    .addComponent(querierNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuerierMoblieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuerierMoblieLable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partitiontLabel)
                .addGap(29, 29, 29)
                .addComponent(recordedFilesCheckBox)
                .addGap(36, 36, 36)
                .addGroup(QueriesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowButton)
                    .addComponent(cancelButton))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        FormPanel.add(QueriesCard, "card4");

        NewEmployeeLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NewEmployeeLabel1.setText("Nwe employee:");

        NEmployeeNameLabel1.setText("Employee Name:");

        NEmolyeeNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEmolyeeNameField1ActionPerformed(evt);
            }
        });

        EmployeeSSNLabel2.setText("Employee SNN:");

        NEmployeeSSNField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NNEmployeeSSNField1ActionPerformed(evt);
            }
        });

        ClearNewEIButton1.setText("clear");
        ClearNewEIButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearNewEIButton1ActionPerformed(evt);
            }
        });

        NewEmployeeIDLabel1.setText("Employee ID:");

        NewEmployeeIDField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEmployeeIDField1ActionPerformed(evt);
            }
        });

        AddNewEmployeeButton1.setText("Add");
        AddNewEmployeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewEmployeeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewEmployeeCardLayout = new javax.swing.GroupLayout(NewEmployeeCard);
        NewEmployeeCard.setLayout(NewEmployeeCardLayout);
        NewEmployeeCardLayout.setHorizontalGroup(
            NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(NewEmployeeLabel1))
                    .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(AddNewEmployeeButton1)
                                .addGap(18, 18, 18)
                                .addComponent(ClearNewEIButton1))
                            .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NEmployeeNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NewEmployeeIDLabel1)
                                    .addComponent(EmployeeSSNLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NEmolyeeNameField1)
                                    .addComponent(NEmployeeSSNField1)
                                    .addComponent(NewEmployeeIDField1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NewEmployeeCardLayout.setVerticalGroup(
            NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewEmployeeCardLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(NewEmployeeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewEmployeeIDLabel1)
                    .addComponent(NewEmployeeIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEmployeeNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NEmolyeeNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmployeeSSNLabel2)
                    .addComponent(NEmployeeSSNField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(NewEmployeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearNewEIButton1)
                    .addComponent(AddNewEmployeeButton1))
                .addGap(30, 30, 30))
        );

        FormPanel.add(NewEmployeeCard, "card5");

        updateEmplyeeInfoLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updateEmplyeeInfoLabel1.setText("Update employee information:");

        EmployeeIDLabel1.setText("Emplyee ID:");

        jLabel1.setText(" Name:");

        NewNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewNameField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("SNN:");

        NewSNNField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSNNField1ActionPerformed(evt);
            }
        });

        updateButton1.setText("update");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateEmployeeCaredPanel1Layout = new javax.swing.GroupLayout(updateEmployeeCaredPanel1);
        updateEmployeeCaredPanel1.setLayout(updateEmployeeCaredPanel1Layout);
        updateEmployeeCaredPanel1Layout.setHorizontalGroup(
            updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmployeeCaredPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateEmployeeCaredPanel1Layout.createSequentialGroup()
                        .addComponent(updateEmplyeeInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(181, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateEmployeeCaredPanel1Layout.createSequentialGroup()
                        .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateEmployeeCaredPanel1Layout.createSequentialGroup()
                                .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(updateEmployeeCaredPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NewSNNField1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(NewNameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(EmplyeeIdField1))
                        .addGap(31, 31, 31))))
            .addGroup(updateEmployeeCaredPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(updateButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updateEmployeeCaredPanel1Layout.setVerticalGroup(
            updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmployeeCaredPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(updateEmplyeeInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmplyeeIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NewNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateEmployeeCaredPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NewSNNField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(updateButton1)
                .addGap(28, 28, 28))
        );

        FormPanel.add(updateEmployeeCaredPanel1, "card6");

        deletEmployeeLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        deletEmployeeLabel3.setText("Delet employee:");

        EmployeeIdLabel3.setText("Emplyee ID:");

        deletEmployeeButton1.setText("Delet");
        deletEmployeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletEmployeeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletEmplyeeCardLayout = new javax.swing.GroupLayout(DeletEmplyeeCard);
        DeletEmplyeeCard.setLayout(DeletEmplyeeCardLayout);
        DeletEmplyeeCardLayout.setHorizontalGroup(
            DeletEmplyeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletEmplyeeCardLayout.createSequentialGroup()
                .addGroup(DeletEmplyeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeletEmplyeeCardLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(deletEmployeeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeletEmplyeeCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EmployeeIdLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DEmployeeIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeletEmplyeeCardLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(deletEmployeeButton1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        DeletEmplyeeCardLayout.setVerticalGroup(
            DeletEmplyeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletEmplyeeCardLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(deletEmployeeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(DeletEmplyeeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeIdLabel3)
                    .addComponent(DEmployeeIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(deletEmployeeButton1)
                .addGap(31, 31, 31))
        );

        FormPanel.add(DeletEmplyeeCard, "card7");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("Manger:");

        jLabel4.setText("Manger ID:");

        mangerName.setText("Manger Name:");

        mangerNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangerNameTextField1ActionPerformed(evt);
            }
        });

        mangerPssLabel5.setText("Passsword:");

        MSignInButton1.setText("Sgin in");
        MSignInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSignInButton1ActionPerformed(evt);
            }
        });

        MsginOutButton1.setText("sgin out");
        MsginOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsginOutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MangerCardLayout = new javax.swing.GroupLayout(MangerCard);
        MangerCard.setLayout(MangerCardLayout);
        MangerCardLayout.setHorizontalGroup(
            MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MangerCardLayout.createSequentialGroup()
                .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MangerCardLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mangerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mangerPssLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mangerIdTextField1)
                            .addComponent(mangerNameTextField1)
                            .addComponent(mangerPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                    .addGroup(MangerCardLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MangerCardLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(MSignInButton1)
                        .addGap(18, 18, 18)
                        .addComponent(MsginOutButton1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        MangerCardLayout.setVerticalGroup(
            MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MangerCardLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangerIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangerName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangerNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangerPssLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangerPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(MangerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MSignInButton1)
                    .addComponent(MsginOutButton1))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        FormPanel.add(MangerCard, "card8");

        EmployeeMenu.setText("Emolyee");

        mangerMenuItem1.setText("Manger sing in");
        mangerMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangerMenuItem1ActionPerformed(evt);
            }
        });
        EmployeeMenu.add(mangerMenuItem1);

        newEmployeeMenuItem1.setText("New employee");
        newEmployeeMenuItem1.setEnabled(false);
        newEmployeeMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeMenuItem1ActionPerformed(evt);
            }
        });
        EmployeeMenu.add(newEmployeeMenuItem1);

        UpdateInfoMenuItem1.setText("Update information");
        UpdateInfoMenuItem1.setEnabled(false);
        UpdateInfoMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoMenuItem1ActionPerformed(evt);
            }
        });
        EmployeeMenu.add(UpdateInfoMenuItem1);

        deletEmployeeMenuItem1.setText("Delet employee");
        deletEmployeeMenuItem1.setEnabled(false);
        deletEmployeeMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletEmployeeMenuItem1ActionPerformed(evt);
            }
        });
        EmployeeMenu.add(deletEmployeeMenuItem1);

        jMenuBar1.add(EmployeeMenu);

        singOutMenu.setText("sing out");
        jMenuBar1.add(singOutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OwnerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnerNameFieldActionPerformed

    private void AddrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddrButtonActionPerformed

        DogRadioButton.setSelected(false);
        CatRadioButton.setSelected(false);
        FeedingCheckBox.setSelected(false);
        DogWalkingCheckBox.setSelected(false);
        CatBreedingChechBox.setSelected(false);
        HairCutCheckBox.setSelected(false);
        NailClippinCheckBox.setSelected(false);
        VaccineCheckBox.setSelected(false);
        ExaminationChechBox.setSelected(false);
        PersonSpinner.setValue(0);
        CatBreedingChechBox.setEnabled(false);
        DogWalkingCheckBox.setEnabled(false);

    }//GEN-LAST:event_AddrButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

        OwnerNameField.setText("");
        PetNameField.setText("");
        MobileField.setText("");
        DogRadioButton.setSelected(false);
        CatRadioButton.setSelected(false);
        FeedingCheckBox.setSelected(false);
        DogWalkingCheckBox.setSelected(false);
        CatBreedingChechBox.setSelected(false);
        HairCutCheckBox.setSelected(false);
        NailClippinCheckBox.setSelected(false);
        VaccineCheckBox.setSelected(false);
        ExaminationChechBox.setSelected(false);
        PersonSpinner.setValue(0);
        CatBreedingChechBox.setEnabled(false);
        DogWalkingCheckBox.setEnabled(false);
        MobileField.setText("+966");

        //To change body of generated methods, choose Tools | Templates.
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void DogRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogRadioButtonActionPerformed
        if (DogRadioButton.isSelected()) {
            DogWalkingCheckBox.setEnabled(true);
            CatBreedingChechBox.setEnabled(false);
        } else {
            DogWalkingCheckBox.setEnabled(false);
            CatBreedingChechBox.setEnabled(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_DogRadioButtonActionPerformed

    private void CatRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatRadioButtonActionPerformed
        if (CatRadioButton.isSelected()) {
            DogWalkingCheckBox.setEnabled(false);
            CatBreedingChechBox.setEnabled(true);
        } else {
            DogWalkingCheckBox.setEnabled(true);
            CatBreedingChechBox.setEnabled(false);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CatRadioButtonActionPerformed

    private void MobileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void DogWalkingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogWalkingCheckBoxActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_DogWalkingCheckBoxActionPerformed

    private void SingInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingInButtonActionPerformed
        // TODO add your handling code here:
        String employeeID = this.EmployeeIDField1.getText();
        String employeeName = this.EmployeeNameField.getText();
        String employeePss = this.PasswordField.getText();
        Employee employee = new Employee(employeeID, employeeName,employeePss);
        

        if (employee.isEmployeeExist(employeeID) && employee.passworedviled(employeeName, employeePss)) {
            CardLayout services = (CardLayout) this.FormPanel.getLayout();
            services.show(this.FormPanel, "card3");
        } else if (employee.getEmployeeName().equals("") || employee.getEmployeeSSN().equals("")) {
            JOptionPane.showMessageDialog(this, "The name or password you enter is empty",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "The name or password you enter is not correct",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SingInButtonActionPerformed

    private void NEmolyeeNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEmolyeeNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEmolyeeNameField1ActionPerformed

    private void NNEmployeeSSNField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NNEmployeeSSNField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NNEmployeeSSNField1ActionPerformed

    private void NewEmployeeIDField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEmployeeIDField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewEmployeeIDField1ActionPerformed

    private void AddNewEmployeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewEmployeeButton1ActionPerformed
        // TODO add your handling code here:
        Employee employee
                = new Employee(NewEmployeeIDField1.getText(), NEmolyeeNameField1.getText(), NEmployeeSSNField1.getText());
        if (employee.getEmployeeID().equals("") || employee.getEmployeeName().equals("") || employee.getEmployeeSSN().equals("")) {
            JOptionPane.showMessageDialog(this, "The Id or Name or SNN  you enter is empty",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (employee.isEmployeeExist(this.NewEmployeeIDField1.getText())) {
            JOptionPane.showMessageDialog(this, "This employee is Existing",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            employee.saveEmployeeInfo();
            this.NEmolyeeNameField1.setText("");
            this.NEmployeeSSNField1.setText("");
        }
    }//GEN-LAST:event_AddNewEmployeeButton1ActionPerformed

    private void ClearNewEIButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearNewEIButton1ActionPerformed
        // TODO add your handling code here:
        this.NewEmployeeIDField1.setText("");
        this.NEmolyeeNameField1.setText("");
        this.NEmployeeSSNField1.setText("");
    }//GEN-LAST:event_ClearNewEIButton1ActionPerformed

    private void newEmployeeMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout newEmployee = (CardLayout) this.FormPanel.getLayout();
        newEmployee.show(this.FormPanel, "card5");


    }//GEN-LAST:event_newEmployeeMenuItem1ActionPerformed

    private void NewNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewNameField1ActionPerformed

    private void NewSNNField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSNNField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewSNNField1ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        // TODO add your handling code here:
        Employee employee=
                new Employee(this.EmplyeeIdField1.getText(),NewNameField1.getText(),NewSNNField1.getText());
         if (employee.getEmployeeID().equals("") || employee.getEmployeeName().equals("") || employee.getEmployeeSSN().equals("")) {
            JOptionPane.showMessageDialog(this, "The Id or Name or SNN  you enter is empty",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
         else if(!employee.isEmployeeExist(EmplyeeIdField1.getText())){
              JOptionPane.showMessageDialog(this, "This emplyee isn't exit",
                    "Error", JOptionPane.ERROR_MESSAGE);  
         }
         else{
             employee.updateEmployyeInfo(EmplyeeIdField1.getText());
         }
         
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void UpdateInfoMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout updateEmployee = (CardLayout) this.FormPanel.getLayout();
        updateEmployee.show(this.FormPanel, "card6");
    }//GEN-LAST:event_UpdateInfoMenuItem1ActionPerformed

    private void deletEmployeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletEmployeeButton1ActionPerformed
        // TODO add your handling code here:
   Employee employee=new Employee(DEmployeeIDTextField1.getText());
        if(employee.getEmployeeID().equals("")){
             JOptionPane.showMessageDialog(this, "Please enter ID employee",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            employee.deletEmployee(DEmployeeIDTextField1.getText());
        }
    }//GEN-LAST:event_deletEmployeeButton1ActionPerformed

    private void deletEmployeeMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletEmployeeMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout deletEmployee = (CardLayout) this.FormPanel.getLayout();
        deletEmployee.show(this.FormPanel, "card7");
    }//GEN-LAST:event_deletEmployeeMenuItem1ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String ownerName=this.OwnerNameField.getText();
        String ownerMobile=this.MobileField.getText();
        String employeeId=this.EmployeeIDField1.getText();
        Employee employee=new Employee(employeeId);
        Owner owner=new Owner(ownerName,ownerMobile);
        if(owner.getOwnerName().equals("")|| owner.getOwnerMobile().equals("")){
            JOptionPane.showMessageDialog(this, "Please insert all clint information!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        owner.saveOwnerInfo();
        }
        String petName=this.PetNameField.getText();
        String petType;
        Pet pet=new Pet();
        
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void mangerMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangerMenuItem1ActionPerformed
        // TODO add your handling code here:
         CardLayout deletEmployee = (CardLayout) this.FormPanel.getLayout();
        deletEmployee.show(this.FormPanel, "card8");
    }//GEN-LAST:event_mangerMenuItem1ActionPerformed

    private void mangerNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangerNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangerNameTextField1ActionPerformed

    private void MSignInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSignInButton1ActionPerformed
        // TODO add your handling code here:
        String mangerId=this.mangerIdTextField1.getText();
        String mangerName=this.mangerNameTextField1.getText();
        String mangerPss=this.mangerPasswordField1.getText();
        Manger manger=new Manger(mangerId,mangerName);
        
        if (manger.isMangerExit(mangerName)&& manger.passworedviled(mangerName,mangerPss)) {
              this.newEmployeeMenuItem1.setEnabled(true);
              this.UpdateInfoMenuItem1.setEnabled(true);
              this.deletEmployeeMenuItem1.setEnabled(true);
        } else if (manger.getID().equals("") || manger.getName().equals("")) {
            JOptionPane.showMessageDialog(this, "The ID or Name or Password you enter is empty",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "The ID or Name or Password you enter is not correct",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_MSignInButton1ActionPerformed

    private void MsginOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsginOutButton1ActionPerformed
        // TODO add your handling code here:
        this.mangerIdTextField1.setText("");
        this.mangerNameTextField1.setText("");
        this.mangerPasswordField1.setText("");
        this.newEmployeeMenuItem1.setEnabled(false);
        this.UpdateInfoMenuItem1.setEnabled(false);
        this.deletEmployeeMenuItem1.setEnabled(false);
    }//GEN-LAST:event_MsginOutButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petCafeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petCafeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petCafeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petCafeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petCafeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewEmployeeButton1;
    private javax.swing.JButton AddrButton;
    private javax.swing.JLabel CafeServiceLabel;
    private javax.swing.JCheckBox CatBreedingChechBox;
    private javax.swing.JRadioButton CatRadioButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearNewEIButton1;
    private javax.swing.JLabel ClientInfoLabel;
    private javax.swing.JTextField DEmployeeIDTextField1;
    private javax.swing.JPanel DeletEmplyeeCard;
    private javax.swing.JRadioButton DogRadioButton;
    private javax.swing.JCheckBox DogWalkingCheckBox;
    private javax.swing.JLabel EmloyeeInfoLabel;
    private javax.swing.JPanel EmployeeCard;
    private javax.swing.JTextField EmployeeIDField1;
    private javax.swing.JLabel EmployeeIDLabel1;
    private javax.swing.JLabel EmployeeIdLabel3;
    private javax.swing.JMenu EmployeeMenu;
    private javax.swing.JTextField EmployeeNameField;
    private javax.swing.JLabel EmployeeNameLabel;
    private javax.swing.JLabel EmployeePassLabel;
    private javax.swing.JLabel EmployeeSSNLabel2;
    private javax.swing.JLabel EmplyeeIDLabel1;
    private javax.swing.JTextField EmplyeeIdField1;
    private javax.swing.JCheckBox ExaminationChechBox;
    private javax.swing.JCheckBox FeedingCheckBox;
    private javax.swing.JPanel FormPanel;
    private javax.swing.JLabel GroomingLabel;
    private javax.swing.JCheckBox HairCutCheckBox;
    private javax.swing.JButton MSignInButton1;
    private javax.swing.JPanel MangerCard;
    private javax.swing.JTextField MobileField;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JButton MsginOutButton1;
    private javax.swing.JTextField NEmolyeeNameField1;
    private javax.swing.JLabel NEmployeeNameLabel1;
    private javax.swing.JTextField NEmployeeSSNField1;
    private javax.swing.JCheckBox NailClippinCheckBox;
    private javax.swing.JPanel NewEmployeeCard;
    private javax.swing.JTextField NewEmployeeIDField1;
    private javax.swing.JLabel NewEmployeeIDLabel1;
    private javax.swing.JLabel NewEmployeeLabel1;
    private javax.swing.JTextField NewNameField1;
    private javax.swing.JTextField NewSNNField1;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JTextField OwnerNameField;
    private javax.swing.JLabel OwnerNameLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JSpinner PersonSpinner;
    private javax.swing.JLabel PetLabel;
    private javax.swing.JTextField PetNameField;
    private javax.swing.JLabel PetNameLabel;
    private javax.swing.JLabel PetServicesLabel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JLabel QuerierMoblieLable;
    private javax.swing.JTextField QuerierMoblieTextField;
    private javax.swing.JLabel QuerierNameLabel;
    private javax.swing.JPanel QueriesCard;
    private javax.swing.JLabel QueriesLabel;
    private javax.swing.JPanel ServicesCard;
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton SingInButton;
    private javax.swing.JButton SingUpButtom;
    private javax.swing.JMenuItem UpdateInfoMenuItem1;
    private javax.swing.JCheckBox VaccineCheckBox;
    private javax.swing.JLabel VetLabel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deletEmployeeButton1;
    private javax.swing.JLabel deletEmployeeLabel3;
    private javax.swing.JMenuItem deletEmployeeMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField mangerIdTextField1;
    private javax.swing.JMenuItem mangerMenuItem1;
    private javax.swing.JLabel mangerName;
    private javax.swing.JTextField mangerNameTextField1;
    private javax.swing.JPasswordField mangerPasswordField1;
    private javax.swing.JLabel mangerPssLabel5;
    private javax.swing.JMenuItem newEmployeeMenuItem1;
    private javax.swing.JLabel partitiontLabel;
    private javax.swing.JTextField querierNameTextField;
    private javax.swing.JCheckBox recordedFilesCheckBox;
    private javax.swing.JMenu singOutMenu;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateButton1;
    private javax.swing.JPanel updateEmployeeCaredPanel1;
    private javax.swing.JLabel updateEmplyeeInfoLabel1;
    // End of variables declaration//GEN-END:variables

}
